theme = "HaleBopp"
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Anna Lunterova'


[params]
description = "This is development of Anna's portfolio website through Hugo"

[[menus.main]]
url=""
name="Portfolio"

[[menus.main]]
url=""
name="Writings"

[[menus.main]]
url=""
name="About"
