theme = "HaleBopp"
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'


[params]
description = "This is development of Anna's portfolio website"

[[menus.main]]
url=""
name="Portfolio"

[[menus.main]]
url=""
name="Writings"

[[menus.main]]
url=""
name="About"
